const PDFDocument = require("pdfkit");
const BottleEntry = require("../models/BottleEntry");
const MonthlySummary = require("../models/MonthlySummary");

exports.generateMonthlyPDF = async (req, res, next) => {
  try {
    const { month, year } = req.query;
    if (!month || !year) {
      return res.status(400).json({ message: "Month and year required" });
    }

    const monthNames = [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ];
    const monthIndex = Number(month) - 1;
    const monthName = monthNames[monthIndex] || "Unknown";

    // Fetch summary and entries
    const summary =
      (await MonthlySummary.findOne({
        month: Number(month),
        year: Number(year),
      })) || {};
    const entries =
      (await BottleEntry.find({
        month: Number(month),
        year: Number(year),
      }).sort({ date: 1 })) || [];

    const doc = new PDFDocument({ margin: 30, size: "A4" });

    // Send PDF to client
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=MonthlyReport-${monthName}-${year}.pdf`,
    );
    doc.pipe(res);

    // --- HEADER ---
    doc.fontSize(18).text("Water Bottle Tracker Report", {
      align: "center",
      underline: true,
    });
    doc.moveDown(0.5);
    doc.fontSize(14).text(`Month: ${monthName} ${year}`, { align: "center" });
    doc.moveDown(1);

    // --- SUMMARY ---
    doc
      .fontSize(12)
      .font("Helvetica-Bold")
      .text("Monthly Summary", { underline: true });
    doc.moveDown(0.5);
    doc.font("Helvetica");
    doc.text(`Total Bottles: ${summary.total_bottles || 0}`);
    doc.text(`Delivery Days: ${summary.delivery_days || 0}`);
    doc.text(`Total Amount: ₹${summary.total_amount || 0}`);
    doc.moveDown(1);

    // --- TABLE ---
    const tableTop = doc.y;
    const columnPositions = [50, 150, 250, 350];

    // Table header
    doc.font("Helvetica-Bold");
    const headers = ["Date", "Bottles", "Price", "Amount"];
    headers.forEach((h, i) => doc.text(h, columnPositions[i], tableTop));
    doc.moveDown();
    let y = tableTop + 20;

    doc.font("Helvetica");

    let totalBottles = 0;
    let totalAmount = 0;

    entries.forEach((e, index) => {
      // Alternate row background
      if (index % 2 === 0) {
        doc.rect(45, y - 2, 500, 20).fill("#f0f0f0");
      }

      // Text color solid black
      doc.fillColor("black");

      const dateStr = e.date
        ? new Date(e.date).toISOString().split("T")[0]
        : "-";
      doc.text(dateStr, columnPositions[0], y);
      doc.text(e.bottle_count || 0, columnPositions[1], y);
      doc.text(e.price_per_bottle || 0, columnPositions[2], y);
      doc.text(e.amount || 0, columnPositions[3], y);

      // Calculate totals
      totalBottles += e.bottle_count || 0;
      totalAmount += e.amount || 0;

      y += 20;

      // Automatic page break
      if (y > 750) {
        doc.addPage();
        y = 50;
      }
    });

    // Total row at bottom
    doc.moveTo(45, y).lineTo(545, y).stroke();
    y += 5;
    doc.font("Helvetica-Bold");
    doc.text("TOTAL", columnPositions[0], y);
    doc.text(totalBottles, columnPositions[1], y);
    doc.text("-", columnPositions[2], y);
    doc.text(totalAmount, columnPositions[3], y);

    // --- FOOTER ---
    doc.moveDown(4);
    doc.fontSize(10).text(
      `Generated by Water Bottle Tracker System 
                      by Aptech Solutions`,
      {
        align: "center",
        opacity: 0.6,
      },
    );

    doc.end();
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message });
  }
};
